config/routes.rb
Rails.application.routes.draw do
root to: 'cocktails#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails do
    resources :doses, only: [:new, :create]
  end

  # post '/cocktails', to: 'cocktails#create', as: 'create_cocktail'

  resources :doses, only: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
    mount_uploader :photo, PhotoUploader
    
    has_many :doses, dependent: :destroy
    has_many :ingredients, through: :doses
    validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :ingredient, :uniqueness => { :scope => :cocktail }

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :doses
    validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
    before_action :find_cocktail, only: [:show, :destroy]

    def index
        @cocktails = Cocktail.all
    end
    

    def show
        @dose = Dose.new
    end
    
      # GET /cocktail/new
    def new
        @cocktail = Cocktail.new
    end
    
      # POST /restaurants
      # POST /restaurants.json
    def create
        @cocktail = Cocktail.create(cocktail_params)
        if @cocktail.save
            redirect_to cocktail_path(@cocktail)
          else
            # if invalid the object now has errors inside it.
            render :new
          end
    end

    private


    def cocktail_params
        params.require(:cocktail).permit(:name, :photo)
    end

    def find_cocktail
        @cocktail = Cocktail.find(params[:id])
    end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
    before_action :find_dose, only: [:show]
      # GET /dose/new
    def new
        @dose = Dose.new
    end
    
      # POST /restaurants
      # POST /restaurants.json
    def create
        @cocktail = Cocktail.find(params[:cocktail_id])
        @dose = Dose.create(dose_params)
        @dose.cocktail = @cocktail
        if @dose.save
            redirect_to cocktail_path(@cocktail)
          else
            # if invalid the object now has errors inside it.
            render 'cocktails/show'
          end
    end

    def destroy
        @dose = Dose.find(params[:id])
        @dose.destroy
        redirect_to cocktail_path(@dose.cocktail)
    end

    private


    def dose_params
        params.require(:dose).permit(:description, :ingredient_id)
    end

    def find_dose
        @dose = Dose.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<h1>List of cocktails</h1>
    <% @cocktails.each do |cocktail| %>
    <h3><%= link_to cocktail.name, cocktail_path(cocktail) %></h3>
    <%= cl_image_tag cocktail.photo, height: 300, width: 400, crop: :fill %>
    <% end %>
    
<p><%= link_to 'Create a new cocktail', new_cocktail_path %></p>

app/views/cocktails/new.html.erb
<h1>New cocktail page</h1>

<%= simple_form_for(@cocktail) do |f| %>
  <%#= f.error_notification %>
  <%#= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
  </div>
  <div class="form-actions btn btn-dark">
    <%= f.button :submit %>
  </div>
  
<% end %>

app/views/cocktails/show.html.erb
   <h5 ><%= @cocktail.name %></h5>
       <% @cocktail.doses.each do |dose| %>
         <li>
        <%= dose.ingredient.name %>
        <%= dose.description %>
        <%= cl_image_tag @cocktail.photo, height: 300, width: 400, crop: :fill %>
            <%= link_to '✄', dose_path(dose), method: :delete %>
         </li>
       <% end %>
       <%= simple_form_for [@cocktail, @dose] do |f| %>
         <%= f.input :description %>
         <%= f.association :ingredient %>
         <%= f.button :submit, class:'btn-primary'%>
         <%= link_to 'Back to cocktails', cocktails_path, class:'btn btn-primary'  %>
       <% end %>

app/views/doses/new.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%#= f.error_notification %>
  <%#= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :description %>
    <%= f.association :ingredient %>
  </div>

  <div class="form-actions btn btn-dark">
    <%= f.button :submit %>
  </div>
  
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>